import type { KnipConfig } from 'knip';

const config: KnipConfig = {
    entry: [
        'src/bootstrap.ts',       // Dev/server bootstrap (imports index)
        'src/index.ts',           // MCP server entry
        'src/cli/index.ts',       // CLI bin entry
        'src/metrics-server.ts',  // Standalone metrics server
        'src/ui/main.tsx',        // UI entry (Vite)
        'scripts/**/*.{ts,mjs}',  // Build-time scripts
        'eslint.config.cjs',      // ESLint entry (loads @typescript-eslint/*)
        'eslint/flat-config.cjs',
    ],
    project: [
        'src/**/*.ts',
        'src/ui/**/*.{ts,tsx}',
        'scripts/**/*.{ts,mjs}',
        // Include tests so devDeps used only in tests (e.g. testcontainers in keycloak-container.ts)
        // are not reported as unused.
        'tests/**/*.ts',
        'tests/ui/**/*.{ts,tsx}',
    ],
    ignore: [
        'dist/**',
        'src/embed-docs/**',      // Generated at build time
        // Generated by scripts/build-embed-docs.ts. Getters (getTemplates, getTools, getMem, getTemplate,
        // listResourceKeys) are part of the MCP resource API and may be used by MCP clients or
        // tooling; they are not imported in src, so knip reports them as unused.
        'src/resources/embedded-mcp-resources.ts',
        // Vite ambient types and module declarations; not imported by source
        'src/ui/vite-env.d.ts',
        // Zod schema modules: tool input/output shapes; some exports are only for MCP hosts / tests
        'src/tools/**/*_schema.ts',
    ],
    ignoreDependencies: [
        // Loaded via createRequire in src/cli/keyring.ts (dynamic require for ESM)
        '@napi-rs/keyring',
        // Optional @tiptap/react peers pinned as direct runtime dependencies so the
        // published package cannot resolve a mixed-version TipTap peer graph.
        '@tiptap/extension-bubble-menu',
        '@tiptap/extension-floating-menu',
        // Runtime tools used in scripts/shell, not imported directly
        'dotenv-cli',
        'pino-pretty',
        'concurrently',
        // UI build: used by Vite/PostCSS config, not imported in source
        '@tailwindcss/postcss',
        'autoprefixer',
        'tailwindcss',
        // Mermaid CLI: used in scripts/validate-mermaid.sh (shell script, not tracked by Knip)
        '@mermaid-js/mermaid-cli',
    ],
    // Knip reports "Unlisted binaries: python3" because it's referenced in package.json scripts
    // but not declared as a dependency. It's a system binary used by infra:up for Keycloak
    // realm setup (scripts/deploy-configure-keycloak-realms.py).
    ignoreBinaries: ['python3'],
    ignoreExportsUsedInFile: true,
};

export default config;
